//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Std
{
    [Serializable]
    public class MultiArrayLayoutMsg : Message
    {
        public const string k_RosMessageName = "std_msgs/MultiArrayLayout";
        public override string RosMessageName => k_RosMessageName;

        public MultiArrayDimensionMsg[] dim;
        public uint data_offset;

        public MultiArrayLayoutMsg()
        {
            this.dim = new MultiArrayDimensionMsg[0];
            this.data_offset = 0;
        }

        public MultiArrayLayoutMsg(MultiArrayDimensionMsg[] dim, uint data_offset)
        {
            this.dim = dim;
            this.data_offset = data_offset;
        }

        public static MultiArrayLayoutMsg Deserialize(MessageDeserializer deserializer) => new MultiArrayLayoutMsg(deserializer);

        private MultiArrayLayoutMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dim, MultiArrayDimensionMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.data_offset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.dim);
            serializer.Write(this.dim);
            serializer.Write(this.data_offset);
        }

        public override string ToString()
        {
            return "MultiArrayLayoutMsg: " +
            "\ndim: " + System.String.Join(", ", dim.ToList()) +
            "\ndata_offset: " + data_offset.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
